from autoresirch.session_manager.shared.analysis import (
    record_agent_analysis,
    write_run_synopsis,
    write_session_summary,
)
from autoresirch.prepare import run_experiment
from autoresirch.session_manager.constants import (
    AGENT_ANALYSIS_FAILURE_MIN_WORDS,
    AGENT_ANALYSIS_MAX_FACTORS,
    AGENT_ANALYSIS_MAX_FACTOR_WORDS,
    AGENT_ANALYSIS_MAX_NEXT_STEP_WORDS,
    AGENT_ANALYSIS_MAX_WORDS,
    AGENT_ANALYSIS_MIN_WORDS,
    ANALYSIS_INPUT_METRIC_ORDER,
    ANALYSIS_SCHEMA_VERSION,
    EDITABLE_TRAIN_FILE,
    INTERPRETATION_AUC_SPAN_DELTA,
    INTERPRETATION_METRIC_ORDER,
    INTERPRETATION_METRIC_SPECS,
    INTERPRETATION_NEAR_MISS_AUC_DELTA,
    INTERPRETATION_RMSE_SPAN_DELTA,
    PROGRAM_FILE,
    REPO_ROOT,
    RUN_LOG,
    SESSION_RESULTS_HEADER,
    SESSIONS_DIR,
)
from autoresirch.session_manager.shared.orchestration import (
    create_session,
    finalize_session,
    run_session_experiment,
    sync_train_to_incumbent,
)
from autoresirch.session_manager.schemas import (
    AgentAnalysisRecord,
    AnalysisInputRecord,
    DecisionRecord,
    InterpretationMetricSpec,
    MetricDeltaView,
    RunContext,
    RunIntent,
    SessionContext,
    SessionState,
    SessionSummaryRecord,
)
from autoresirch.session_manager.shared.storage import (
    _collect_git_metadata,
    _load_architecture_metadata,
    _session_results_path,
    _session_summary_json_path,
    _session_summary_md_path,
    allocate_run_dir,
    append_session_results_row,
    load_session_context,
    load_session_state,
    save_session_context,
    save_session_state,
    write_decision_record,
    write_run_context,
    write_train_snapshot,
)


def main(argv=None):
    from autoresirch.session_manager.cli import main as cli_main

    return cli_main(argv)

__all__ = [
    "AgentAnalysisRecord",
    "AGENT_ANALYSIS_FAILURE_MIN_WORDS",
    "AGENT_ANALYSIS_MAX_FACTORS",
    "AGENT_ANALYSIS_MAX_FACTOR_WORDS",
    "AGENT_ANALYSIS_MAX_NEXT_STEP_WORDS",
    "AGENT_ANALYSIS_MAX_WORDS",
    "AGENT_ANALYSIS_MIN_WORDS",
    "_collect_git_metadata",
    "_load_architecture_metadata",
    "_session_results_path",
    "_session_summary_json_path",
    "_session_summary_md_path",
    "allocate_run_dir",
    "AnalysisInputRecord",
    "ANALYSIS_INPUT_METRIC_ORDER",
    "ANALYSIS_SCHEMA_VERSION",
    "append_session_results_row",
    "create_session",
    "DecisionRecord",
    "EDITABLE_TRAIN_FILE",
    "finalize_session",
    "InterpretationMetricSpec",
    "INTERPRETATION_AUC_SPAN_DELTA",
    "INTERPRETATION_METRIC_ORDER",
    "INTERPRETATION_METRIC_SPECS",
    "INTERPRETATION_NEAR_MISS_AUC_DELTA",
    "INTERPRETATION_RMSE_SPAN_DELTA",
    "load_session_context",
    "load_session_state",
    "main",
    "MetricDeltaView",
    "PROGRAM_FILE",
    "record_agent_analysis",
    "REPO_ROOT",
    "run_experiment",
    "run_session_experiment",
    "RunContext",
    "RunIntent",
    "RUN_LOG",
    "save_session_context",
    "save_session_state",
    "SessionContext",
    "SessionState",
    "SESSION_RESULTS_HEADER",
    "SESSIONS_DIR",
    "SessionSummaryRecord",
    "sync_train_to_incumbent",
    "write_decision_record",
    "write_run_context",
    "write_run_synopsis",
    "write_session_summary",
    "write_train_snapshot",
]
