from __future__ import annotations

from pathlib import Path

from autoresirch.session_manager.shared.metrics import (
    SESSION_RESULTS_HEADER,
    STANDARD_ANALYSIS_INPUT_METRIC_ORDER,
    STANDARD_INTERPRETATION_METRIC_ORDER,
    STANDARD_INTERPRETATION_METRIC_SPECS,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
SESSIONS_DIR = REPO_ROOT / "sessions"
EDITABLE_TRAIN_FILE = REPO_ROOT / "autoresirch" / "train.py"
PROGRAM_FILE = REPO_ROOT / "autoresirch" / "program.md"
RUN_LOG = REPO_ROOT / "run.log"

INTERPRETATION_NEAR_MISS_AUC_DELTA = 0.005
INTERPRETATION_AUC_SPAN_DELTA = 0.08
INTERPRETATION_RMSE_SPAN_DELTA = 0.05
ANALYSIS_SCHEMA_VERSION = 1
AGENT_ANALYSIS_MAX_WORDS = 180
AGENT_ANALYSIS_MIN_WORDS = 15
AGENT_ANALYSIS_FAILURE_MIN_WORDS = 5
AGENT_ANALYSIS_MAX_FACTORS = 3
AGENT_ANALYSIS_MAX_FACTOR_WORDS = 16
AGENT_ANALYSIS_MAX_NEXT_STEP_WORDS = 80

INTERPRETATION_METRIC_SPECS = STANDARD_INTERPRETATION_METRIC_SPECS
INTERPRETATION_METRIC_ORDER = STANDARD_INTERPRETATION_METRIC_ORDER
ANALYSIS_INPUT_METRIC_ORDER = STANDARD_ANALYSIS_INPUT_METRIC_ORDER
